### ISSUE TITLE
Brak folderu mod

### ISSUE THREAD

**Issue by mateuszkadlubowski** [Niukron/Crusader-Kings-3-Spolszczenie#1]
Niestety nie ma u mnie folderu mod w podanej lokalizacji. Sam go utworzyłem ale to nadal nie działa.

Jest jakieś znane rozwiązanie tego? Co w takim przypadku?

**Comment by Niukron** [comment]
Chodzi o folder C:\Users\[User]\Documents\Paradox Interactive\Crusader Kings III\mod ? 

Proszę uruchomić laucher i zainstalować obojętnie jaki mod z paradox mods. Jeśli to nie pomoże to sam nie wiem jaki może być powód.
