### ISSUE TITLE
Spolszczenie nie działa.

### ISSUE THREAD

**Issue by hrb14** [Niukron/Crusader-Kings-3-Spolszczenie#3]
Witam. 

Wszystko zrobione tak jak trzeba a mimo to spolszczenie nie działa na laptopie (na komputerze stacjonarnym śmiga bez problemów). Instalowałem grę już kilka razy, usuwałem folder paradoxu przed każdym reinstalem i nic. Czy to normalne, że folder "mod" trzeba utworzyć własnoręcznie ? Jakieś podpowiedzi, pomysły jak rozwiązać problem ?

Z góry dziękuje.

**Comment by Niukron** [comment]
Jeśli nie został stworzony przez launcher to możesz spróbować ręcznie utworzyć. Jak to nie pomoże to ostateczna metoda to skopiowanie zawartości folderów moda zgodnie ze strukturą folderów w głównym folderze gry bezpośrednio do głównego folderu gry. W takim wypadku również zawartość folderu replace musisz podnieść o stopień do góry. Jak zobaczysz strukturę plików moda i gry to zrozumiesz. A najlepiej zainstaluj przez paradoxmods lub steam workshop - wtedy powinno zadziałać bez problemów.

**Comment by hrb14** [comment]
dziękuje za odpowiedź.

Pozdrawiam i wielkie dzięki za spolszczenie. Good Job ;)
